### ISSUE TITLE
Unable to start either [demo_myvariant.docker, old_myvariant.docker]

### ISSUE THREAD

**Issue by bwalsh** [biothings/biothings.api#13]
Following instructions from http://docs.biothings.io/en/latest/doc/standalone.html#quick-links
Both images exhibit the same behavior:
* hub not starting
  * curl http://localhost:19200/_cat/indices (returns nothing)
* inability to ssh from host to container
* inability to start hub cli

Host information:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

$ docker --version
Docker version 17.12.1-ce, build 7390fc6

$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 84
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: v0.13.0 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-22-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 118GiB
Name: bmeg-build
ID: JRG3:XIRP:VOMU:Z5IM:CBNN:M2TT:QP6J:TE4G:B6V4:C5KI:RZ6T:S7ZX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

```

# docker run --name old_myvariant -p 19080:80 -p 19200:9200 -p 19022:7022 -p 19090:7080 -d old_myvariant
2171a1bd50736f4074c9c3102282ae4b92a8002335347217d65a5e8681b49c3f
root@jupyterhub:/mnt/walsbr#  curl -v http://localhost:19080/metadata
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 19080 (#0)
> GET /metadata HTTP/1.1
> Host: localhost:19080
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Date: Fri, 13 Jul 2018 20:11:23 GMT
< Content-Type: text/html; charset=UTF-8
< Content-Length: 93
< Connection: keep-alive
< Server: TornadoServer/4.5.1
<
* Connection #0 to host localhost left intact
<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>root@jupyterhub:/mnt/walsbr#


root@jupyterhub:/mnt/walsbr#  curl http://localhost:19200/_cat/indices

root@jupyterhub:/mnt/walsbr#  ssh guest@localhost -p 19022
ssh_exchange_identification: read: Connection reset by peer


root@jupyterhub:/mnt/walsbr# docker exec -it old_myvariant bash


Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/biothings/myvariant.info/src/biothings/bin/autohub.py", line 16, in <module>
    biothings.config_for_app(config)
  File "/home/biothings/myvariant.info/src/biothings/__init__.py", line 55, in config_for_app
    check_config(config_mod)
  File "/home/biothings/myvariant.info/src/biothings/__init__.py", line 32, in check_config
    raise ConfigurationError("%s: %s" % (attr,str(getattr(config_mod,attr))))
biothings.ConfigurationError: DATA_PLUGIN_FOLDER: Define path to folder which will contain all 3rd party parsers, dumpers, etc...
(pyenv) biothings@2171a1bd5073:~/myvariant.info/src$

```

**Comment by sirloon** [comment]
Hi Brian,
Thanks for reporting this. We recently migrated to ElasticSeach 6.x (previously using 2.4), standalone instances are « broken » since then, I’m working on it and should be able to provide a fix probably next week

**Comment by bwalsh** [comment]
Thanks Sebastien.

2.4 -> 6.x is a big jump.  nice work.

**Comment by sirloon** [comment]
Hi Brian. I updated myvariant standalone instance for "old" data, if you get a chance, can you give it a try using that link (not the one on the documentation) ?

https://s3-us-west-2.amazonaws.com/biothings-containers/old_myvariant/old_myvariant_old-standalone-old-standalone-20180716.docker

"old" instances will still run ES2.4 though, not ES6 just fyi, because we're using an index/snapshot done on this version. The docker image above is just about running a old version of myvariant, before the ES6 migration.

"demo" and "production" instances will run latest code as well as ES6, I hope to release something soon, hopefully this week.

**Comment by bwalsh** [comment]
Thank you. Feels like we are getting further:

**Comment by sirloon** [comment]
Great, did you get an index and a running API in this end ? `update_old_hg19()` will restore a ES snapshot, it'll take few hours depending on your server and bandwidth.

Also, few tips: because we have 2 indices for myvariant (like 2 sources, hg19 & hg38) all commands have a old_hg19 and old_hg38  suffix. command `versions()` doesn't exist (the output from `help()` shows available commands). About `versions_old_hg19()`, `info_*` and `check_`, those commands are async, you'll have to press return again to get the actual results once the commands have run. Confusing but I didn't find an easy way to workaround that. I'm assuming you trim some of the output because I don't see all the results for invoking these commands.

Anyways, let me know if you have been able to get a running API.

Finally, I've been able to fix the demo standalone, you can give a shot if you want: http://biothings-containers.s3-website-us-west-2.amazonaws.com/demo_myvariant/demo_myvariant:standalone_v2.docker. I may update the image again to improve few things but overall everything is there.

**Comment by bwalsh** [comment]
I've just been able to get back to this.
Continue to make progress, ran into this:

```
[1] RUN {51m54.02s} update_old_hg19()
hub> kex protocol error: type 7 seq 342
[1] RUN {1h15m3.31s} update_old_hg19()
[3] OK  info_old_hg19(): finished
>>> Current local version: 'None'
>>> Release note for remote version 'latest':
No information found for release 'latest'
```

**Comment by sirloon** [comment]
damn... The first "update_old_hg19()" should work, I'll test it again to see if I can reproduce. What would help is posting the logs (found in /data/variant.info/logs/).

**Comment by sirloon** [comment]
@bwalsh so I could reproduce the issue, which seems to be a problem in reporting the versions:

```
hub> info_old_hg19()
[2] RUN {0.0s} info_old_hg19()
hub> 
[2] OK  info_old_hg19(): finished 
>>> Current local version: 'None'
>>> Release note for remote version 'latest':
No information found for release 'latest'
hub> 
```

This should definitely reports actual local version and latest remote versions available. The logs though shows the index was successfully created (in /data/myvariant.info/logs/upload_biothings_old_hg19_YYYYMMDD.log):

```
21:26:27 [191:MainThread] - biothings_old_hg19_upload - INFO -- Recovery status for index 'biothings_current_old_hg19': {'status': 'IN_PROGRESS', 'progress': '85.00%'}
21:27:27 [191:MainThread] - biothings_old_hg19_upload - INFO -- Recovery status for index 'biothings_current_old_hg19': {'status': 'IN_PROGRESS', 'progress': '90.00%'}
21:28:27 [191:MainThread] - biothings_old_hg19_upload - INFO -- Recovery status for index 'biothings_current_old_hg19': {'status': 'DONE', 'progress': '100%'}
21:28:27 [191:MainThread] - biothings_old_hg19_upload - INFO -- Snapshot 'myvariant_current_201607_hg19' successfully restored to index 'biothings_current_old_hg19' (host: 'localhost:9200')
21:28:27 [191:MainThread] - biothings_old_hg19_upload - INFO -- success [steps=data,post,master,clean]
```

As long as the hub doesn't report an error, I think it's safe to use the data.  I'll close this issue will fix the problem about the versions reporting in another one for clarity, but feel free to reopen it as needed regarding other problems.

**Comment by bwalsh** [comment]
The load seems to stall ( it has been in this state for 12 hrs )


```
# df /data
Filesystem      1K-blocks      Used Available Use% Mounted on
/dev/vdb       1290016920 382978832 841485704  32% /data

# curl localhost:9200/_cat/indices
red    open biothings_current_old_hg19 20 1 306090034 0 356.5gb 356.5gb
yellow open hubdb                       5 1         1 0   7.7kb   7.7kb

# tail  upload_biothings_old_hg19_201
14:57:05 [182:MainThread] - biothings_old_hg19_upload - INFO -- Recovery status for index 'biothings_current_old_hg19': {'progress': '90.00%', 'status': 'IN_PROGRESS'}
14:58:05 [182:MainThread] - biothings_old_hg19_upload - INFO -- Recovery status for index 'biothings_current_old_hg19': {'progress': '90.00%', 'status': 'IN_PROGRESS'}
14:59:05 [182:MainThread] - biothings_old_hg19_upload - INFO -- Recovery status for index 'biothings_current_old_hg19': {'progress': '90.00%', 'status': 'IN_PROGRESS'}
15:00:05 [182:MainThread] - biothings_old_hg19_upload - INFO -- Recovery status for index 'biothings_current_old_hg19': {'progress': '90.00%', 'status': 'IN_PROGRESS'}
15:01:05 [182:MainThread] - biothings_old_hg19_upload - INFO -- Recovery status for index 'biothings_current_old_hg19': {'progress': '90.00%', 'status': 'IN_PROGRESS'}
15:02:05 [182:MainThread] - biothings_old_hg19_upload - INFO -- Recovery status for index 'biothings_current_old_hg19': {'progress': '90.00%', 'status': 'IN_PROGRESS'}
15:03:05 [182:MainThread] - biothings_old_hg19_upload - INFO -- Recovery status for index 'biothings_current_old_hg19': {'progress': '90.00%', 'status': 'IN_PROGRESS'}
15:04:05 [182:MainThread] - biothings_old_hg19_upload - INFO -- Recovery status for index 'biothings_current_old_hg19': {'progress': '90.00%', 'status': 'IN_PROGRESS'}
15:05:05 [182:MainThread] - biothings_old_hg19_upload - INFO -- Recovery status for index 'biothings_current_old_hg19': {'progress': '90.00%', 'status': 'IN_PROGRESS'}
15:06:05 [182:MainThread] - biothings_old_hg19_upload - INFO -- Recovery status for index 'biothings_current_old_hg19': {'progress': '90.00%', 'status': 'IN_PROGRESS'}


# curl localhost:9200/_cat/recovery
hubdb                      0  519      store    done  172.17.0.2 172.17.0.2 n/a             n/a                           0   100.0% 0           100.0% 1   159         0 100.0% 0
hubdb                      1  666      store    done  172.17.0.2 172.17.0.2 n/a             n/a                           0   100.0% 0           100.0% 1   159         0 100.0% 0
hubdb                      2  589      store    done  172.17.0.2 172.17.0.2 n/a             n/a                           0   100.0% 0           100.0% 1   159         0 100.0% 0
hubdb                      3  666      store    done  172.17.0.2 172.17.0.2 n/a             n/a                           0   100.0% 0           100.0% 1   159         0 100.0% 0
hubdb                      4  808      store    done  172.17.0.2 172.17.0.2 n/a             n/a                           0   100.0% 0           100.0% 4   7311        0 100.0% 0
biothings_current_old_hg19 0  2130591  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 109 100.0% 21383237390 100.0% 109 21383237390 0 100.0% 0
biothings_current_old_hg19 1  2037927  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 121 100.0% 21221200588 100.0% 121 21221200588 0 100.0% 0
biothings_current_old_hg19 2  74063117 snapshot index n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 133 11.3%  21132467627 32.5%  133 21132467627 0 100.0% 0
biothings_current_old_hg19 3  2066505  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 133 100.0% 21163983987 100.0% 133 21163983987 0 100.0% 0
biothings_current_old_hg19 4  2247940  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 106 100.0% 21050931041 100.0% 106 21050931041 0 100.0% 0
biothings_current_old_hg19 5  2239302  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 121 100.0% 21129275811 100.0% 121 21129275811 0 100.0% 0
biothings_current_old_hg19 6  2303259  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 127 100.0% 21414334736 100.0% 127 21414334736 0 100.0% 0
biothings_current_old_hg19 7  1996205  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 124 100.0% 21406234308 100.0% 124 21406234308 0 100.0% 0
biothings_current_old_hg19 8  2068018  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 133 100.0% 21208244057 100.0% 133 21208244057 0 100.0% 0
biothings_current_old_hg19 9  2117498  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 127 100.0% 21502670056 100.0% 127 21502670056 0 100.0% 0
biothings_current_old_hg19 10 2246955  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 127 100.0% 21458677544 100.0% 127 21458677544 0 100.0% 0
biothings_current_old_hg19 11 67689163 snapshot index n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 115 5.2%   21149513848 2.9%   115 21149513848 0 100.0% 0
biothings_current_old_hg19 12 2460087  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 109 100.0% 21207137298 100.0% 109 21207137298 0 100.0% 0
biothings_current_old_hg19 13 2160053  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 118 100.0% 21323982435 100.0% 118 21323982435 0 100.0% 0
biothings_current_old_hg19 14 2045474  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 115 100.0% 21276371077 100.0% 115 21276371077 0 100.0% 0
biothings_current_old_hg19 15 2191769  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 127 100.0% 21115394804 100.0% 127 21115394804 0 100.0% 0
biothings_current_old_hg19 16 2048647  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 112 100.0% 20717179416 100.0% 112 20717179416 0 100.0% 0
biothings_current_old_hg19 17 1986077  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 130 100.0% 21480416531 100.0% 130 21480416531 0 100.0% 0
biothings_current_old_hg19 18 2191040  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 115 100.0% 21508186738 100.0% 115 21508186738 0 100.0% 0
biothings_current_old_hg19 19 2122957  snapshot done  n/a        172.17.0.2 variant_old_url myvariant_current_201607_hg19 130 100.0% 21304809299 100.0% 130 21304809299 0 100.0% 0

# grep 90.00% upload_biothings_old_hg19_20180813.log | wc -l
952

```

**Comment by bwalsh** [comment]
Manually dropped index.  Retrying apply_old_hg19().  Let's see if second time works

**Comment by sirloon** [comment]
Weird, did you see anything in elasticsearch logs ? It seems related to elastic only, or maybe the server is too small ? (RAM, CPU, ?)

**Comment by bwalsh** [comment]
Elastic search logs were clean.
Current host: 6 VCPU, 30GB

```
# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: v0.13.0 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-30-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 29.45GiB
Name: walsbr-test
ID: JRG3:XIRP:VOMU:Z5IM:CBNN:M2TT:QP6J:TE4G:B6V4:C5KI:RZ6T:S7ZX
Docker Root Dir: /mnt/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by sirloon** [comment]
I'm running out of ideas. Your hardware is definitely enough to run this. I tried on a 2xlarge instance on AWS (32GiB RAM) w/ 1TB storage, it worked in quite a reasonable amount of time (< 2h iirc). Is there any IT policy regarding data downloading, and something on the server that would renice/slow a process if running for too long at high cpu? You could try to trigger the restore manually from the ES server directly, but I doubt this would make a difference, the hub does that and the command seems valid... I don't know, like I said I'm running out of idea :)

**Comment by bwalsh** [comment]
@sirloon Thanks for the support.  Like you suggested, I ran the container on AWS, no problems. Thanks again.
