### ISSUE TITLE
Crawler error: too many files open

### ISSUE THREAD

**Issue by lhannest** [biothings/biothings.api#15]
http://biothings.io/explorer/api/v2/crawler?input_type=mondo&input_value=0018911

```
Traceback (most recent call last):
  File "/home/ubuntu/opt/devpy3/lib/python3.5/site-packages/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/ubuntu/opt/biothings_explorer_web/src/handlers/entitycrawler.py", line 282, in get
    results = exploreinput(input_type, input_value)
  File "/home/ubuntu/opt/biothings_explorer_web/src/handlers/entitycrawler.py", line 170, in exploreinput
    jsonld_docs.append(jh.json2jsonld(json_doc['data'], jsonld_context_path))
  File "/home/ubuntu/opt/biothings_explorer_web/src/biothings_explorer/jsonld_processor.py", line 149, in json2jsonld
    jsonld_context = readFile(jsonld_context_path)
  File "/home/ubuntu/opt/biothings_explorer_web/src/biothings_explorer/utils.py", line 32, in readFile
OSError: [Errno 24] Too many open files: '/home/ubuntu/opt/biothings_explorer_web/src/biothings_explorer/openapi_specs/biolink/jsonld_context/biolink_disease_phenotype.json'
```

**Comment by lhannest** [comment]
Now no data is coming back:
http://biothings.io/explorer/api/v2/crawler?input_type=mondo&input_value=0018911
```
{
    "linkedData": {}
}
```

**Comment by kevinxin90** [comment]
@lhannest Hi Lance, thanks for pointing that out! It's currently fixed. Btw, if you would like to open an issue for BioThings Explorer next time, please use the biothings explorer [github repo](https://github.com/biothings/biothings_explorer). This repo is for another project in our lab.

**Comment by sirloon** [comment]
closing this issue as it's related to explorer, not biothings.api
