### ISSUE TITLE
Broken reference to  `biothings.web.BiothingsAPIApp` prevents hub from starting up

### ISSUE THREAD

**Issue by ravila4** [biothings/biothings.api#156]
When I try to start up the hub on my local computer with the latest code changes, I see this error, caused by https://github.com/biothings/biothings.api/blob/master/biothings/hub/api/manager.py#L88:

```
Traceback (most recent call last):
  File "/home/ravila/Software/miniconda/envs/mygeneset/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ravila/Software/miniconda/envs/mygeneset/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ravila/Projects/mygeneset.info/src/bin/hub.py", line 22, in <module>
    server.start()
  File "/home/ravila/Projects/mygeneset.info/src/biothings/biothings/hub/__init__.py", line 474, in start
    self.configure()
  File "/home/ravila/Projects/mygeneset.info/src/biothings/biothings/hub/__init__.py", line 414, in configure
    self.configure_managers()
  File "/home/ravila/Projects/mygeneset.info/src/biothings/biothings/hub/__init__.py", line 781, in configure_managers
    getattr(self, "configure_%s_manager" % feat)()
  File "/home/ravila/Projects/mygeneset.info/src/biothings/biothings/hub/__init__.py", line 655, in configure_api_manager
    api_manager = APIManager(**args)
  File "/home/ravila/Projects/mygeneset.info/src/biothings/biothings/hub/api/manager.py", line 24, in __init__
    self.restore_running_apis()
  File "/home/ravila/Projects/mygeneset.info/src/biothings/biothings/hub/api/manager.py", line 42, in restore_running_apis
    self.start_api(api["_id"])
  File "/home/ravila/Projects/mygeneset.info/src/biothings/biothings/hub/api/manager.py", line 88, in start_api
    app = biothings.web.BiothingsAPIApp(config_module=config_mod)
AttributeError: module 'biothings.web' has no attribute 'BiothingsAPIApp'

```

I am not sure why this issue didn't on the show up when I was testing on the pre-production server (su06)

**Comment by zcqian** [comment]
Probably related to 1a4befd3e5a851edc108f3a6ca1090ae810dfc97
