### ISSUE TITLE
Indexer cannot recognize `LinkDataBuilder. target_backend`

### ISSUE THREAD

**Issue by erikyao** [biothings/biothings.api#178]
Error messages are like:

```bash
Aug 12 21:35:45 su06 python[68443]: INFO:tornado.access:200 OPTIONS /index (172.29.80.35) 0.97ms
Aug 12 21:35:46 su06 python[68443]: DEBUG:indexmanager:<class 'biothings.hub.dataindex.indexer.Indexer'>
Aug 12 21:35:46 su06 python[68443]: ERROR:tornado.application:Uncaught exception PUT /index (172.29.80.35)
Aug 12 21:35:46 su06 python[68443]: HTTPServerRequest(protocol='http', host='localhost:19080', method='PUT', uri='/index', version='HTTP/1.1', remote_ip='172.29.80.35')
Aug 12 21:35:46 su06 python[68443]: Traceback (most recent call last):
Aug 12 21:35:46 su06 python[68443]:   File "/opt/home/pending/venv/lib/python3.6/site-packages/tornado/web.py", line 1704, in _execute
Aug 12 21:35:46 su06 python[68443]:     result = await result
Aug 12 21:35:46 su06 python[68443]:   File "<string>", line 69, in put
Aug 12 21:35:46 su06 python[68443]:   File "/opt/home/pending/venv/src/biothings/biothings/hub/dataindex/indexer.py", line 593, in index
Aug 12 21:35:46 su06 python[68443]:     idx = idx(build_doc, indexer_env_, target_name, index_name)
Aug 12 21:35:46 su06 python[68443]:   File "/opt/home/pending/venv/src/biothings/biothings/hub/dataindex/indexer.py", line 152, in __init__
Aug 12 21:35:46 su06 python[68443]:     assert build_doc.get("target_backend") in ('mongo', None)
Aug 12 21:35:46 su06 python[68443]: AssertionError
Aug 12 21:35:46 su06 python[68443]: ERROR:tornado.access:500 PUT /index (172.29.80.35) 3.04ms
```

A `LinkDataBuilder` would have `target_backend = 'link'`, which cannot be recognized by the indexer. A sample `src_build` entry for a `LinkDataBuilder` is like:

```bash
> db.src_build.findOne({'_id': 'idisk_20210812_sicwkhq0'})
{
	"_id" : "idisk_20210812_sicwkhq0",
	"target_backend" : "link",
	"target_name" : "idisk_20210812_sicwkhq0",
	"backend_url" : [
		"src",
		"iDisk"
	],
	"build_config" : {
		"_id" : "idisk",
		"name" : "idisk",
		"doc_type" : "umls",
		"sources" : [
			"iDisk"
		],
		"root" : [
			"iDisk"
		],
		"builder_class" : "biothings.hub.databuild.builder.LinkDataBuilder"
	},
	"sources" : [
		"iDisk"
	],
        # Omitted
}
```

**Comment by namespacestd0** [comment]
Resolved in https://github.com/biothings/biothings.api/commit/fed9dca2457f7a2caa3ec74e4676edd657274659.
