### ISSUE TITLE
[low priority] AIOHttp Session is Closed on `/status`

### ISSUE THREAD

**Issue by zcqian** [biothings/biothings.api#199]
Stack trace (which isn't exactly helpful because the session is closed elsewhere)

```
Oct 22 14:53:38 $HOSTNAME python[16841]: [WARNING elasticsearch:303] GET http://es.example.org:9200/_nodes/_all/http [status:N/A request:0.000s]
Oct 22 14:53:38 $HOSTNAME python[16841]:     Traceback (most recent call last):
Oct 22 14:53:38 $HOSTNAME python[16841]:       File "$APP_ROOT/.env/lib/python3.6/site-packages/elasticsearch/_async/http_aiohttp.py", line 301, in perform_request
Oct 22 14:53:38 $HOSTNAME python[16841]:         fingerprint=self.ssl_assert_fingerprint,
Oct 22 14:53:38 $HOSTNAME python[16841]:       File "$APP_ROOT/.env/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
Oct 22 14:53:38 $HOSTNAME python[16841]:         self._resp = await self._coro
Oct 22 14:53:38 $HOSTNAME python[16841]:       File "$APP_ROOT/.env/lib/python3.6/site-packages/aiohttp/client.py", line 357, in _request
Oct 22 14:53:38 $HOSTNAME python[16841]:         raise RuntimeError('Session is closed')
Oct 22 14:53:38 $HOSTNAME python[16841]:     RuntimeError: Session is closed

```

**Comment by newgene** [comment]
close this one as we don't see this issue any more (likely an issue resolved in the recent versions of the elasticsearch python client or its dependencies)
