### ISSUE TITLE
`CursorNotFound` Error in `doc_feeder`

### ISSUE THREAD

**Issue by erikyao** [biothings/biothings.api#282]
A latest MyVariant.info build report the following erorr:

```python
12:55:53 [3188068:MainThread] - build - ERROR -- Failed merging source 'snpeff_hg19': cursor id 5661038325069124923 not found, full error: {
'ok': 0.0, 'errmsg': 'cursor id 5661038325069124923 not found', 'code': 43, 'codeName': 'CursorNotFound'}
Traceback (most recent call last):
  File "/opt/home/myvariant/venv/src/biothings/biothings/hub/databuild/builder.py", line 763, in merged
    res = f.result()
  File "/opt/home/myvariant/venv/src/biothings/biothings/hub/databuild/builder.py", line 936, in merge_source
    for big_doc_ids in id_provider:
  File "/opt/home/myvariant/venv/src/biothings/biothings/utils/mongo.py", line 523, in id_feeder
    for doc_ids in doc_feeder_func():
  File "/opt/home/myvariant/venv/src/biothings/biothings/utils/mongo.py", line 320, in doc_feeder
    for doc in cur:
```

The error is directly raised at [Line 320, function `doc_feeder`, of module `biothings/utils/mongo.py`](https://github.com/biothings/biothings.api/blob/00f697a30f31934cc4c6af3cb49bd36e4abd0d4b/biothings/utils/mongo.py#L320).

The underlying cause of this error is explained at [cursor.noCursorTimeout()](https://www.mongodb.com/docs/manual/reference/method/cursor.noCursorTimeout/). Quote:

> However, if the application takes longer than 30 minutes to process the current batch of documents, the session is marked as expired and closed. When the server closes the session, it also kills the cursor despite the cursor being configured with 
[noCursorTimeout()](https://www.mongodb.com/docs/manual/reference/method/cursor.noCursorTimeout/#mongodb-method-cursor.noCursorTimeout)

The solution is to use sessions explicitly. Also the above link.

**Comment by erikyao** [comment]
Also note that the logging configuration of `doc_feeder` is problematic. 

```python
def doc_feeder(collection, step=1000, s=None, e=None, inbatch=False, query=None, 
               batch_callback=None, fields=None, logger=logging)
```

`doc_feeder` requires a logger instance, and by default it uses the `logging` module, which redirects to the root logger. However in an individual API like MyVariant, the root logger might be overlooked.

A solution is to pass the logger instance explicitly. Two main callers of `doc_feeder` is the [`id_feeder` function](https://github.com/biothings/biothings.api/blob/00f697a30f31934cc4c6af3cb49bd36e4abd0d4b/biothings/utils/mongo.py#L395) and the [`builder` module](https://github.com/biothings/biothings.api/blob/00f697a30f31934cc4c6af3cb49bd36e4abd0d4b/biothings/hub/databuild/builder.py) (which also calls `id_feeder`). We should make sure that a valid logger instance is passed to `doc_feeder` when calling it.

**Comment by erikyao** [comment]
Logging statement revision in `doc_feeder` function:

1. `query` could be a long `$in` operation, so the log on [mongo.py#L362](https://github.com/biothings/biothings.api/blob/b49540d6e29f420114148699e929abfab6a5fa06/biothings/utils/mongo.py#L362) can be turned off.
2. `session.id` is a BSON document like `{'id': Binary(b'\x1d\x8c\x89P\xaf\x92M\xbc\x9fQR.\xf9\x0e\xe9\xa8', 4)}` where `Binary` represent BSON binary data. The tailing `4` is a constant [`bson.binary.UUID_SUBTYPE`](https://api.mongodb.com/python/3.0.2/api/bson/binary.html) indicating that the binary data are [UUID](https://github.com/mongodb/node-mongodb-native/blob/main/src/sessions.ts#L836). Therefore we can log the session UUID as `session.session_id["id"].as_uuid()`

**Comment by newgene** [comment]
released in [0.12.0](https://github.com/biothings/biothings.api/releases/tag/v0.12.0)
