### ISSUE TITLE
Need a more clear error message for manifest.json issues

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#365]
For some common issues in a `manifest.json` file, the CLI currently returns some errors which are not very straightforward to the end users. We should try to catch these issues early and return something more useful.

Here is an example data plugin:
* https://github.com/smazroueeods/mAbsData/tree/db31aaf44385af9edc53192675304b126d13daa2

There are two issues:
1. `uploaders` should be `uploader` here, otherwise, `uploaders` should expect an array as the value.
2. the parser module name is incorrectly referenced: `"parser": "mAb_parser:load_data", `, the value should be `parser:load_data`.

The current error for the first one:
```
[13:24:17] ERROR    Invalidate plugin 'mAbsData' because: Error loading manifest: 'str' object has no attribute 'get'                                                                
                    Traceback (most recent call last):                                                                                                                               
                      File "/.../biothings.api/biothings/hub/dataplugin/assistant.py", line 169, in load_plugin                                                           
                        self.interpret_manifest(manifest, df.as_posix())                                                                                                             
                    AttributeError: 'str' object has no attribute 'get' 
```

The 2nd one returns this error:
```
           ERROR    Invalidate plugin 'mAbsData' because: Error loading manifest: load_data not found in module <module 'mAbsData' (namespace) from ['/tmp/mAbsData']>     
                    Traceback (most recent call last):                                                                                                                               
                      File "/.../biothings.api/biothings/hub/dataplugin/assistant.py", line 169, in load_plugin                                                           
                        self.interpret_manifest(manifest, df.as_posix())                                                                                                             
                    AssertionError: load_data not found in module <module 'mAbsData' (namespace) from ['/tmp/mAbsData']> 
```
This error is actually not too bad, at least it points out an invalid `mAbsData` module correctly. We can see if any room to improve this one as well.

**Comment by ctrl-schaff** [comment]
The first error should now be resolved by the changes from this [PR](https://github.com/biothings/biothings.api/pull/371). The validation would provide the following error message to diagnose manifest issues


```shell
❯ biothings-cli dataplugin dump
[13:22:49] INFO     No memory limit set
           ERROR    Discovered a manifest typing error that prevents loading. Please update the ['uploaders'] section of the manifest. Expected type <array> | Discovered type
                    <object>
                    Traceback (most recent call last):
                      File "/home/schaffjr/workspace/plugin-development/.direnv/python-3.12.3/lib/python3.12/site-packages/biothings/hub/dataplugin/loaders/loader.py", line
                    181, in load_plugin
                        self.validate_manifest(manifest)
                    biothings.hub.dataplugin.loaders.schema.exceptions.ManifestTypeException: Discovered a manifest typing error that prevents loading. Please update the
                    ['uploaders'] section of the manifest. Expected type <array> | Discovered type <object>
Traceback (most recent call last):
  File "/home/schaffjr/workspace/plugin-development/.direnv/python-3.12.3/lib/python3.12/site-packages/biothings/hub/dataplugin/loaders/loader.py", line 158, in validate_manifest
    raise refined_validation_error
biothings.hub.dataplugin.loaders.schema.exceptions.ManifestTypeException: Discovered a manifest typing error that prevents loading. Please update the ['uploaders'] section of the manifest. Expected type <array> | Discovered type <object>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/schaffjr/workspace/plugin-development/.direnv/python-3.12.3/lib/python3.12/site-packages/biothings/hub/dataplugin/loaders/loader.py", line 184, in load_plugin
    raise LoaderException from validation_error
biothings.hub.dataplugin.loaders.loader.LoaderException
```

```shell
❯ biothings-cli dataplugin validate manifest.json
[11:36:30] ERROR    Discovered a manifest typing error that prevents loading. Please update the ['uploaders'] section of the manifest. Expected type <array> | Discovered type
                    <object>
                    Traceback (most recent call last):
                      File "/home/schaffjr/workspace/plugin-development/.direnv/python-3.12.3/lib/python3.12/site-packages/biothings/cli/operations.py", line 517, in
                    validate_manifest
                        manifest_loader.validate_manifest(manifest)
                    biothings.hub.dataplugin.loaders.schema.exceptions.ManifestTypeException: Discovered a manifest typing error that prevents loading. Please update the
                    ['uploaders'] section of the manifest. Expected type <array> | Discovered type <object>
+---------------------------------------------------------------------- Biothings Manifest Validation -----------------------------------------------------------------------+
| * Plugin Name: mAbsData                                                                                                                                                    |
| * Manifest Path: /home/schaffjr/workspace/plugin-development/plugins/mAbsData/manifest.json                                                                                |
| * Valid Manifest: False                                                                                                                                                    |
| * Manifest Error: /home/schaffjr/workspace/plugin-development/plugins/mAbsData/manifest.json doesn't conform to the schema                                                 |
|                                                                                                                                                                            |
+---------------------------------------------------------------------- Biothings Manifest Validation -----------------------------------------------------------------------+
```

The second one I think is clear enough that I don't plan to touch it at the moment
```shell
[13:24:32] INFO     No memory limit set
           ERROR    Invalid plugin 'mAbsData' because: Error loading manifest: No module named 'mAb_parser'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mAbsData.mAb_parser'
```
