### ISSUE TITLE
jmespath: new 500 error scenario? 

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings.api#368]
@DylanWelzel @ctrl-schaff (based on discussion in this [Slack thread](https://suwulab.slack.com/archives/CC19LHAF2/p1735059600683279?thread_ts=1733850009.087889&cid=CC19LHAF2))

While writing queries and testing x-bte annotation in https://github.com/biothings/biothings_explorer/issues/904, I found a query that returns an error: `{"code":500,"success":false,"error":"Internal Server Error","details":"bioactivity"}`. Similar queries worked fine (different uniprot ID used in body and jmespath parameter). 

<details><summary>click to see problematic query</summary>
<p>

```
curl --location --globoff 'https://mychem.info/v1/query?size=1000&fields=drugcentral.bioactivity%2Cdrugcentral.xrefs.umlscui%2Cdrugcentral.synonyms&jmespath_exclude_empty=true&always_list=drugcentral.bioactivity&jmespath=drugcentral.bioactivity%7C[%3F!action_type%20%20%26%26%20length(uniprot[%3Funiprot_id%3D%3D%27P29274%27])%20%3E%20%600%60]' \
--header 'Content-Type: application/json' \
--data '{
    "q": ["P29274"],
    "scopes": "drugcentral.bioactivity.uniprot.uniprot_id"
}'
```

</p>
</details> 

<details><summary>Johnathan confirmed that this error could be reproduced locally, and a more specific error message was "KeyError: 'bioactivity'"</summary>
<p>

```
[ERROR tornado.application:1875] Uncaught exception POST /v1/query?size=1000&fields=drugcentral.bioactivity%2Cdrugcentral.xrefs.umlscui%2Cdrugcentral.synonyms&jmespath_exclude_empty=true&always_list=drugcentral.bioactivity&jmespath=drugcentral.bioactivity%7C[%3F!action_type%20%20%26%26%20length(uniprot[%3Funiprot_id%3D%3D%27P29274%27])%20%3E%20%600%60] (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/v1/query?size=1000&fields=drugcentral.bioactivity%2Cdrugcentral.xrefs.umlscui%2Cdrugcentral.synonyms&jmespath_exclude_empty=true&always_list=drugcentral.bioactivity&jmespath=drugcentral.bioactivity%7C[%3F!action_type%20%20%26%26%20length(uniprot[%3Funiprot_id%3D%3D%27P29274%27])%20%3E%20%600%60]', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/jschaff/workspace/biothings/lib/python3.10/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/home/jschaff/workspace/biothings/lib/python3.10/site-packages/biothings/web/handlers/query.py", line 204, in _method
        return await coro(*args, **kwargs)
      File "/home/jschaff/workspace/biothings/lib/python3.10/site-packages/biothings/web/handlers/query.py", line 264, in post
        result = await ensure_awaitable(self.pipeline.search(**self.args))
      File "/home/jschaff/workspace/biothings/lib/python3.10/site-packages/biothings/web/handlers/query.py", line 197, in ensure_awaitable
        return await obj
      File "/home/jschaff/workspace/biothings/lib/python3.10/site-packages/biothings/web/query/pipeline.py", line 103, in _
        return await func(*args, **kwargs)
      File "/home/jschaff/workspace/biothings/lib/python3.10/site-packages/biothings/web/query/pipeline.py", line 176, in search
        result = self.formatter.transform(response, **options)
      File "/home/jschaff/workspace/biothings/lib/python3.10/site-packages/biothings/web/query/formatter.py", line 200, in transform
        responses = [self.transform(res, **options) for res in response]
      File "/home/jschaff/workspace/biothings/lib/python3.10/site-packages/biothings/web/query/formatter.py", line 200, in <listcomp>
        responses = [self.transform(res, **options) for res in response]
      File "/home/jschaff/workspace/biothings/lib/python3.10/site-packages/biothings/web/query/formatter.py", line 253, in transform
        self._transform_hit(hit, options)
      File "/home/jschaff/workspace/biothings/lib/python3.10/site-packages/biothings/web/query/formatter.py", line 303, in _transform_hit
        self.trasform_jmespath(path, obj, doc, options)
      File "/home/jschaff/workspace/biothings/lib/python3.10/site-packages/biothings/web/query/formatter.py", line 469, in trasform_jmespath
        idx_to_remove = [i for i, _obj in enumerate(obj) if not _obj[target_field]]
      File "/home/jschaff/workspace/biothings/lib/python3.10/site-packages/biothings/web/query/formatter.py", line 469, in <listcomp>
        idx_to_remove = [i for i, _obj in enumerate(obj) if not _obj[target_field]]
    KeyError: 'bioactivity'
```

</p>
</details> 

Based on our digging so far, I think this error occurs when this query meets all of this criteria: 
* retrieves a document with a specific structure ([example: this is one doc the problematic query retrieves](https://mychem.info/v1/query?q=_id:OEYIOHPDSNJKLS-UHFFFAOYSA-N))
    1. `drugcentral` exists and its value is an array of objects, rather than an object. Johnathan found 39 documents with this structure. 
    2. **Some** of those `drugcentral` objects have the `bioactivity` field and others don't. 
* the query has the parameter `jmespath_exclude_empty=true`. If you try taking it out, the query then returns without an error....but will keep the hits that didn't pass the criteria specified in `jmespath` (`bioactivity` is `[]` or `null`). I wanted those hits removed, and that's what `jmespath_exclude_empty: true` was supposed to do. 

I think the next steps are to investigate how `jmespath_exclude_empty=true` behavior works and perhaps change its behavior.

**Comment by colleenXu** [comment]
This is problematic because an unknown number of queries will error and retrieve nothing: 
* querying for <=39 chemicals whose documents have that structure (`drugcentral` array where some objects have the `bioactivity` field and others don't) 
* querying for any uniprot IDs (and action_type value or absence) that end up retrieving >= 1 of those chemical documents

**Comment by colleenXu** [comment]
Extra info from our Slack discussion:

<details><summary>A: Trying to set all drugcentral values to an array of objects</summary>
<p>

Dylan [recommended](https://suwulab.slack.com/archives/CC19LHAF2/p1735065280973059?thread_ts=1733850009.087889&cid=CC19LHAF2) turning all drugcentral values into arrays by setting jmespath to ```drugcentral[].bioactivity[] | [? !action_type && length(uniprot[?uniprot_id=='P29274']) > `0`]```. This doesn't seem to work: the query does return without error, but the jmespath logic doesn't seem to have been applied (there's bioactivity objects with the action_type field and with the uniprot_id =/=  P29274). 

<details><summary>drugcentral[].bioactivity[] query</summary>
<p>

```
curl --location --globoff \
  'https://mychem.info/v1/query?size=1000&fields=drugcentral.bioactivity%2Cdrugcentral.xrefs.umlscui%2Cdrugcentral.synonyms&jmespath_exclude_empty=true&always_list=drugcentral.bioactivity&jmespath=drugcentral%5B%5D.bioactivity%5B%5D%7C%5B%3F%20%21action_type%20%20%26%26%20length(uniprot%5B%3Funiprot_id%3D%3D%27P29274%27%5D)%20%3E%20%600%60%5D' \
  --header 'Content-Type: application/json' \
  --data '{
    "q": ["P29274"],
    "scopes": "drugcentral.bioactivity.uniprot.uniprot_id"
}'
```

</p>
</details> 

I then tried doing `always_list:drugcentral,drugcentral.bioactivity` instead. It does turn all drugcentral values into arrays in the response, but the 500 error still happens. 

</p>
</details>

**Comment by rjawesome** [comment]
try this jmespath: ``drugcentral | to_array(@)[] | merge(@, {"bioactivity":bioactivity|[? !action_type && length(uniprot[?uniprot_id=='P29274']) > `0`]}) | [? !!bioactivity]``
(the target field here is "drugcentral", it converts it to an array and then edits the bioactivity field to remove noncompliant entries, finally it removes individual elements of drugcentral that do not have any bioactivity entries)
note: `.drugcentral[]` doesn't convert to an array, it simply just flattens the array if it exists or otherwise returns null

**Comment by colleenXu** [comment]
@rjawesome 

Interesting. Did you use certain websites/resources to figure this out? If so, it'd really help me if you linked them (I know very little syntax >.<). 

Even if there's a jmespath-built-in solution for this, I think it's still helpful to do the "next steps" I put in the opening issue (check the API documents, understand BioThings APIs' behavior for `jmespath` and `jmespath_exclude_empty`...)

**Comment by rjawesome** [comment]
@colleenXu 
I used the JMESPath spec (https://jmespath.org/specification.html) with a bit of help from ChatGPT and also read some of the BioThings API code. 

The main useful aspects from the spec: @ refers to the current object, merge can combine two objects, to_array is the correct way to convert anything to an array if it isn't already. 

I'll try to send a summary of my investigations into jmespath/exclude_empty soon.

**Comment by rjawesome** [comment]
my understanding of jmespath behavior based on reading the code (someone else can correct me if I am wrong, [code](https://github.com/biothings/biothings.api/blob/81d769e0967d34a93810f17421209036aadf0db4/biothings/web/query/formatter.py#L439))

jmespath format: ``path.to.parent.field.target_field|jmespathquery``
jmespath query is run on the ``target_field``, in this example the ``bioactivity`` field inside ``drugcentral``
NOTE: target field & parent field are not in jmespath syntax, it is just a dot-seperated path (ie. ``drugcentral[].bioactivity[]`` as part of the parent or target fields literally looks for the fields ``drugcentral[]`` and ``bioactivity[]`` rather than array conversion/flattenning)

jmespath exclude behavior ([code](https://github.com/biothings/biothings.api/blob/81d769e0967d34a93810f17421209036aadf0db4/biothings/web/query/formatter.py#L468)): 
1. if the parent_field (``drugcentral``) is an array, then it will filter that array to remove any elements with empty target_field (``bioactivity``), and only remove the document from the result if the parent_field (``drugcentral``) is empty after this filtering
2. if the parent_field (``drugcentral``) is not an array, then the document will be excluded from the result if the target_field (``biaoctivity``) is empty/null

my assumption of what the patch is (I don't have a local setup):
- the code `` _obj[target_field]`` mentioned in the error ([line](https://github.com/biothings/biothings.api/blob/81d769e0967d34a93810f17421209036aadf0db4/biothings/web/query/formatter.py#L469)), should probably be changed to ``_obj.get(target_field)``
- this would not throw an error if target_field doesn't exist, rather it would return ``None`` (a falsy value in python);
- this fix would exclude any values from the result where the target_field (``bioactivity``) is missing (if ``jmespath_exclude_empty`` is enabled)

**Comment by colleenXu** [comment]
### Update

I reviewed a list of documents where drugcentral's value may be an array (from @ctrl-schaff, [lab Slack](https://suwulab.slack.com/archives/CC19LHAF2/p1735316281439289?thread_ts=1733850009.087889&cid=CC19LHAF2)).

#### Here's my conclusions:
* most of the time, it seemed fine/valid for `drugcentral` to be an array. When it seemed odd, I noted it in https://github.com/biothings/mychem.info/issues/191 for later review. 
* I don't think the list was fully-accurate. Some entries in the list didn't have `drugcentral` array values in the live API (ex: 1699G8679Z, AVT680JB39, P188ANX8CK) 

#### I also found some documents that would be good for testing. 

<details><summary>Documents where some drugcentral items have bioactivity, some don't</summary>
<p>

- https://mychem.info/v1/chem/AJPJDKMHJJGVTQ-UHFFFAOYSA-M: sodium phosphate. Only 2nd item has bioactivity (1, no action_type) 
- https://mychem.info/v1/chem/GNSKLFRGEWLPPA-UHFFFAOYSA-M: potassium phosphate. Only 2nd item has bioactivity (1, no action_type) 

</p>
</details> 

<details><summary>All drugcentral items have bioactivity (but contents slightly diff), can see how BTE behaves with them</summary>
<p>

- https://mychem.info/v1/chem/IZTQOLKUZKXIRV-YRVFCXMDSA-N: Sincalide/Cholecystokinin (not sure if it's ok they're together)
- https://mychem.info/v1/chem/SEEPANYCNGTZFQ-UHFFFAOYSA-N: sulfadiazine

</p>
</details>

**Comment by colleenXu** [comment]
@rjawesome and co...

I tested the [jmespath string](https://github.com/biothings/biothings.api/issues/368#issuecomment-2564064881) and it didn't seem to work. I used the query from the opening post and made a small change to `fields` (`=drugcentral` in case the full object was needed)...and then adjusted the `jmespath` value. 

When I directly copied Rohan's jmespath string, it looked like jmespath didn't run on the response at all. The response had bioactivity objects with action_type fields and with uniprot IDs that weren't `P29274`. 

<details><summary>Direct-copy query</summary>
<p>

```
curl --location --globoff 'https://mychem.info/v1/query?size=1000&fields=drugcentral&jmespath_exclude_empty=true&always_list=drugcentral.bioactivity&jmespath=drugcentral%20%7C%20to_array(%40)[]%20%7C%20merge(%40%2C%20{%22bioactivity%22%3Abioactivity%7C[%3F%20!action_type%20%26%26%20length(uniprot[%3Funiprot_id%3D%3D%27P29274%27])%20%3E%20%600%60]})%20%7C%20[%3F%20!!bioactivity]' \
--header 'Content-Type: application/json' \
--data '{
    "q": ["P29274"],
    "scopes": "drugcentral.bioactivity.uniprot.uniprot_id"
}'
```

</p>
</details> 

I then tried removing spaces that may be interfering with execution (just there for readability). If the space between `drugcentral` and `|` is removed, a status 400 JMESPathTypeError occurs. 

<details><summary>query, plus saved response with error message</summary>
<p>

```
curl --location --globoff 'https://mychem.info/v1/query?size=1000&fields=drugcentral&jmespath_exclude_empty=true&always_list=drugcentral.bioactivity&jmespath=drugcentral%7Cto_array(%40)[]%7Cmerge(%40%2C{%22bioactivity%22%3Abioactivity%7C[%3F!action_type%20%26%26%20length(uniprot[%3Funiprot_id%3D%3D%27P29274%27])%3E%600%60]})%7C[%3F!!bioactivity]%20%20' \
--header 'Content-Type: application/json' \
--data '{
    "q": ["P29274"],
    "scopes": "drugcentral.bioactivity.uniprot.uniprot_id"
}'
```

[jmespath_error_response.json](https://github.com/user-attachments/files/18284859/jmespath_error_response.json)

</p>
</details>

**Comment by colleenXu** [comment]
@DylanWelzel @ctrl-schaff 

I saw the linked PR, and I'm wondering what the next steps are. 

If the next steps involve running queries on a dev server that uses that PR, maybe it'd be helpful to do that in a meeting together (so I can give feedback on responses/we can adjust queries immediately)?

**Comment by rjawesome** [comment]
> @rjawesome and co...
> 
> I tested the [jmespath string](https://github.com/biothings/biothings.api/issues/368#issuecomment-2564064881) and it didn't seem to work. I used the query from the opening post and made a small change to `fields` (`=drugcentral` in case the full object was needed)...and then adjusted the `jmespath` value.
> 
> When I directly copied Rohan's jmespath string, it looked like jmespath didn't run on the response at all. The response had bioactivity objects with action_type fields and with uniprot IDs that weren't `P29274`.
> 
> Direct-copy query
> I then tried removing spaces that may be interfering with execution (just there for readability). If the space between `drugcentral` and `|` is removed, a status 400 JMESPathTypeError occurs.
> 
> query, plus saved response with error message

whoops, I sent the wrong query. This was the one that was working for me (the merge function is mapped on all the drugcentral elements)
``drugcentral|to_array(@)|map(&merge(@, {"bioactivity": bioactivity|[? !action_type && length(uniprot[?uniprot_id=='P29274']) > `0`]}), @)|[? !!bioactivity]``

**Comment by colleenXu** [comment]
Update!

According to @DylanWelzel, MyChem has been updated to include https://github.com/biothings/biothings.api/pull/372. The other APIs haven't been updated yet. 

I tested the following documents/queries and all worked as-expected (no 500 errors, response data is correct)! So I think the PR fully addresses this problem.  
* https://mychem.info/v1/chem/OEYIOHPDSNJKLS-UHFFFAOYSA-N?fields=drugcentral: opening post's query; "Extra info" post sections B, D, E
* "Extra info" post section C
* ["Good example" documents ](https://github.com/biothings/biothings.api/issues/368#issuecomment-2566904315)

(I also tested x-bte annotation/integration with BTE and things looked mostly good there. One issue linked to https://github.com/biothings/mychem.info/issues/191)
